### ISSUE TITLE
There is not affect for the table secure rule

### ISSUE THREAD

**Issue by pandaxxt** [spacecloud-io/space-cloud#1567] opened 2021-07-02 09:37 UTC
### Describe the bug
1, Go to Storage - Database - Settings - Default rules for tables/collections 
    Create the default  secure rule, the  create -- deny
2, Go to Storage - Database 
    Select one table and click "Secure", click "Add rules", create -- allow
3, Call graphQL API to insert one record in this table, there is the error:

    {
      "message": "Unable to parse token, token is malformed"
    }
4, Update the default  secure rule, the  create -- allow
5, repeat the #3, it is success.

### Your environment
- Space Cloud version: v0.21.4 
- OS: Centos 7.6
- Kubernetes or Docker: Docker
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by sharadregoti** [comment] 2021-08-28 11:46
@pandaxxt I am closing this issue, as I was not able to reproduce this.

**Closed by sharadregoti** 2021-08-28 11:46 UTC
Labels: 🐛 bug, area/gateway
